####################################################################################
# Repository > Settings > Secrets:
#   for Unit Test
#     GOOGLE_SERVICE_ACCOUNT_JSON       : Google Service Account JSON File.
#     GOOGLE_API_KEY                    : Unit Test API Key.
####################################################################################
name: "go module Unit Test"
on:
  push:
    branches:
      - master
      - feature/**
      - v**
    tags:
      - v**
jobs:
  go-test:
    name: "Go module test"
    runs-on: ubuntu-22.04
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    env:
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{secrets.GOOGLE_SERVICE_ACCOUNT_JSON}}
      GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
    steps:
      - uses: actions/checkout@v2.0.0
      - name: "environments / Service Account"
        run: |
          mkdir private
          echo $GOOGLE_SERVICE_ACCOUNT_JSON > "private/service-account.json"
      - name: "environments / Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go
      - name: "environments"
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "PWD=$PWD"
          go version
          ls -al
      - name: "Golang / mod"
        run: go mod tidy
      - name: "Golang / format"
        run: |
          if [ "`go fmt "<<parameters.check-path>>" | grep ".go"`" != "" ]; then
            echo "go format error."
            echo "run -> go fmt <<parameters.check-path>>"
            exit 1
          fi
      - name: "Golang / test"
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/private/service-account.json"
          go test ./...
